name: CI of CentroidalControlCollection (standalone)

on:
  push:
    branches:
      - '**'
    paths-ignore:
    - doc/**
    - README.md
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        build-type: [Debug, RelWithDebInfo]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set environment variables
      run: |
        set -e
        set -x
        echo "LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt-mirrors:
            mc-rtc:
              cloudsmith: mc-rtc/head
          apt: cmake libqpsolvercollection-dev libforcecontrolcollection-dev libnmpc-dev libmc-rtc-dev libgtest-dev
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
